node('GUI-Builder') {
    cleanWs()

    stage('Clone sources') {
        parallel JethroGUIBackend: {
                checkout(
                    [$class: 'GitSCM',
                        branches: [
                            [name: '$Branch']
                        ],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [$class: 'RelativeTargetDirectory',
                                relativeTargetDir: '$Branch/JethroGUIBackend'
                            ],
                            [$class: 'CleanBeforeCheckout']
                        ],
                        submoduleCfg: [],
                        userRemoteConfigs: [
                            [credentialsId: '7cf4f71c-34af-4252-be92-2a445e7b0e18',
                                url: 'https://github.com/JethroDataATE/JethroGUIBackend'
                            ]
                        ]
                    ]
                )
            }, JethroGUI: {
                checkout(
                    [$class: 'GitSCM',
                        branches: [
                            [name: '$Branch']
                        ],
                        doGenerateSubmoduleConfigurations: false,
                        extensions: [
                            [$class: 'RelativeTargetDirectory',
                                relativeTargetDir: '$Branch/JethroGUI'
                            ],
                            [$class: 'CleanBeforeCheckout']
                        ],
                        submoduleCfg: [],
                        userRemoteConfigs: [
                            [credentialsId: '7cf4f71c-34af-4252-be92-2a445e7b0e18',
                                url: 'https://github.com/JethroDataATE/JethroGUI'
                            ]
                        ]
                    ]
                )
            },
            failFast: false
    }

    stage('Build Client') {
            sh "export PATH=/home/ec2-user/.nvm/versions/node/v6.10.1/bin/:$PATH && cd  $Branch/JethroGUI && npm install" 
            sh "export PATH=/home/ec2-user/.nvm/versions/node/v6.10.1/bin/:$PATH && cd  $Branch/JethroGUI && npm run build" 
            // sh "export PATH=/home/ec2-user/.nvm/versions/node/v6.10.1/bin/:$PATH && cd  $Branch/JethroGUI && npm run test" 
    }

    stage('Build Server') {
        sh "chmod a+x $Branch/JethroGUIBackend/resources/scripts/build/make_new.sh"
        sh "$Branch/JethroGUIBackend/resources/scripts/build/make_new.sh $Branch $OS \"Jethro_Manager_CI_Pipeline\""
    }

    // stage('Test') {
    //     echo 'testing'
    // }

    stage('Deploy') {
        echo 'deploying'
        sh "scripts/deploy_to_s3.sh $Branch/JethroGUIBackend/rpmbuild/RPMS/x86_64/ $RPM_DEPLOYMENT_URL updateLatest"
    }

    stage('Build Docker') {
        echo 'Building Docker'
        sh "deocker build "
    }

    stage('Deploy Docker') {
        echo 'deploying'
    }
}