# Jethro over Docker (for HADOOP) 

# based on centos(7):latest image
FROM centos:7

WORKDIR /jethro_install

COPY Common/dockerBootstrap /jethro_install

# install systemd
RUN yum -y update; yum clean all
RUN yum -y install systemd initscripts

# install ssh
RUN yum -y install openssh openssh-server openssl openssh-clients

# Install utilities
RUN yum -y install which wget vim crontabs

# hadoop distributed
ENV HADOOP_PREFIX /etc/hadoop
ENV HADOOP_NAME_NODE_ADDRESS localhost:8080
ENV HADOOP_CONF_DIR $HADOOP_PREFIX/conf
RUN test -d $HADOOP_CONF_DIR || mkdir -p $HADOOP_CONF_DIR
COPY Common/HADOOP/core-site.xml.template $HADOOP_CONF_DIR/core-site.xml.template
COPY Common/HADOOP/conf-site.kerberos.xml.template $HADOOP_CONF_DIR/conf-site.kerberos.xml.template

# install Kerberos client
RUN yum -y install krb5-workstation krb5-libs krb5-auth-dialog
COPY Common/HADOOP/krb5.conf.template /etc/krb5.conf.template
ADD Common/HADOOP/ensureKerberos.sh /jethro_install
RUN chmod +x /jethro_install/ensureKerberos.sh

# Kerberos variables
ENV KERBEROS_DEFAULT_RLM ""
ENV KERBEROS_SERVER ""
ENV KERBEROS_PRINCIPAL ""
ENV KERBEROS_KEYTAB_PATH ""

# User mode parameters
ENV USER_ID 501 
ENV GROUP_ID 501

# change jethro user/group mode
RUN groupadd jethro --gid $GROUP_ID
RUN adduser jethro --uid $USER_ID --gid $GROUP_ID
RUN echo jethro | passwd jethro --stdin
ENV JETHRO_INSTALL_USER=jethro
ENV JETHRO_INSTALL_GROUP=jethro


# SSH key generation parameters
ENV KEY_PATH "" 
ENV GENERAT_KEY_IF_NOT_EXIST "false"

# configure volumes
RUN mkdir /jethro -m 777
RUN mkdir /jethro/persist -m 777
RUN mkdir /jethro/instance_cache -m 777
VOLUME ["/jethro/persist", "/opt/jethro/instances", "/var/log/jethro", "/jethro/instance_cache"]

# Docker run options
ENV INSTANCE_NAME ""
ENV INSTANCE_STORAGE_PATH ""
ENV INSTANCE_CACHE_PATH "/home/jethro/instances_cache"
ENV INSTANCE_CACHE_SIZE "0G"
ENV RUN_JETHRO_MANAGER ""

# start container
RUN chmod a+x /jethro_install/dockerBootstrap
ENTRYPOINT ["sh", "-c", "/jethro_install/dockerBootstrap"]

# expose needed port numbers
EXPOSE 9100-9200 22