#!/bin/bash
#
# Jethro Manager docker bootstarp script

runBackgroudInit(){
  sleep 5

  echo "Lunching Jethro Manager ..."

  JETHROMNG_HOME=/opt/jethro/jethromng
  NODE_PATH=$JETHROMNG_HOME/node
  PM2=$JETHROMNG_HOME/node_modules/.bin/pm2
  export PATH=$NODE_PATH/bin:$PATH

  service jethromng stop >/dev/null 2>&1
  $PM2 kill >/dev/null 2>&1
  pkill PM2 >/dev/null 2>&1
  chmod -R 777 /opt/jethro/jethromng/pm2/ >/dev/null 2>&1
  su - jethro -c "service jethromng start >/dev/null 2>&1"
  service jethromng start

  echo  
  echo "Jethro Manager Docker is up! you can start browsing Jethro Manager appliction."
  echo "In order to ssh the container - use the predefined ssh port (see docker inpect commnad to see all mapped ports)."

}


echo configuring jethro manager docker environment...

runBackgroudInit &

exec /usr/sbin/init 
