node('GUI-Builder') {

    try {
        
        cleanWs()

         withEnv(['VERSION='+ env.VERSION, 'RPM_NAME='+ env.RPM_NAME, 'HADDOP_DEST='+ env.HADDOP_DEST, 'HADDOP_DEST_VERSION='+ env.HADDOP_DEST_VERSION, 'JAVA_VERSION='+ env.JAVA_VERSION]) {

            stage('Clone Sources') {

                checkout(
                    [$class: 'GitSCM', branches: [[name: '*/master']],
                    browser: [$class: 'GithubWeb', repoUrl: 'https://github.com/JethroDataATE/DevOps'],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [
                        [$class: 'SparseCheckoutPaths', sparseCheckoutPaths: [[path: 'Docker/Jethro']]]
                    ],
                    submoduleCfg: [],
                    userRemoteConfigs: [[credentialsId: '7cf4f71c-34af-4252-be92-2a445e7b0e18', url: 'https://github.com/JethroDataATE/DevOps']]]
                )
                    
            }

            stage('Build Docker') {
                echo 'Building Docker' 
                RPM_NAME = RPM.substring(RPM.lastIndexOf("/")+1)
                echo "RPM_NAME: $RPM_NAME"
                VERSION = RPM_NAME.substring(7, RPM_NAME.lastIndexOf(".x86_64.rpm"))
                echo "VERSION: $VERSION" 
                sh "cd Docker/Jethro/ && docker build -t jethrodata/jethro --build-arg JETHRO_RPM_LOACTION=$RPM -f $Hadoop_Distribution/Dockerfile ."   
            }

            stage('Deploy Docker') {
                echo 'deploying tp docker hub'
                sh "docker login --username=iziko --password=pass@word3"
                sh "docker tag jethrodata/jethro:latest jethrodata/jethro:$VERSION"
                sh "docker push jethrodata/jethro:latest"
                sh "docker push jethrodata/jethro:$VERSION"
                echo "Uploading dopcker image to S3"
                echo "VERSION: $VERSION"
                def imageFileName = "dockerDeploy/jethro_docker-$VERSION" + ".tar"
                sh "mkdir dockerDeploy && docker save --output $imageFileName jethrodata/jethro"
                def deploymentTarget = RPM.substring(8,RPM.lastIndexOf("/"))
                echo "deploymentTarget: $deploymentTargetVERSION"
                def bucketName = deploymentTarget.substring(0, deploymentTarget.firstIndexOf("."))
                echo "bucketName: $bucketName"
                def bucketPath = deploymentTarget.substring(deploymentTarget.firstIndexOf("/"))
                echo "bucketPath: $bucketPath"
                def targetPath = "s3://$bucketName/$bucketPath"
                echo "targetPath: $targetPath"
                sh "aws s3 cp dockerDeploy/ $targetPath"
            }
        }
        currentBuild.result = 'SUCCESS'
    }
    catch (any) {
        echo "Build faild: $any"
        currentBuild.result = 'FAILURE'
    }
    // finally {
    //         def buildres = currentBuild.result;
    //         echo "build res: $buildres"
    //         emailext attachLog: true, 
    //         body: "See ${env.BUILD_URL}", 
    //         compressLog: true,
    //         mimeType: 'text/html',
    //         recipientProviders: [[$class: 'DevelopersRecipientProvider']],
    //         replyTo: 'ui@jethrodata.com',
    //         subject: "Jethro docker build has finished with ${currentBuild.result}",
    //         to: 'ui@jethrodata.com'
    // }
}
        